import 'dart:convert';
import 'dart:typed_data';

import 'package:archive/archive.dart';

import 'docx_reader_exception.dart';
import 'models/models.dart';
import 'reader/document_parser.dart';
import 'reader/relationship_resolver.dart';

/// Reads and parses DOCX files into [DocxDocument] objects.
///
/// This is the inverse of [DocxGenerator]: where the generator converts
/// a [DocxDocument] to DOCX bytes, the reader converts DOCX bytes back
/// to a [DocxDocument].
///
/// Example:
/// ```dart
/// final reader = DocxReader();
/// final document = reader.read(docxBytes);
///
/// for (final item in document.content) {
///   if (item is DocxParagraph) {
///     print(item.plainText);
///   }
/// }
/// ```
///
/// Supports reading DOCX files generated by docs_gee as well as files
/// created by Microsoft Word and other DOCX-compatible applications.
///
/// **Limitations:**
/// - Images (`<w:drawing>`) are skipped
/// - Charts and embedded objects are skipped
/// - Complex fields (TOC) are skipped
/// - Column widths are not preserved (not enough info in the XML to
///   reliably reconstruct percentage-based widths)
class DocxReader {
  /// Creates a new [DocxReader].
  const DocxReader();

  /// Parses DOCX bytes into a [DocxDocument].
  ///
  /// Throws [InvalidDocxArchiveException] if [bytes] is not a valid ZIP.
  /// Throws [MissingDocxPartException] if `word/document.xml` is missing.
  /// Throws [InvalidDocxXmlException] if XML content is malformed.
  DocxDocument read(Uint8List bytes) {
    final archive = _decodeArchive(bytes);

    // Extract required parts
    final documentXml = _extractFile(archive, 'word/document.xml');
    if (documentXml == null) {
      throw const MissingDocxPartException('word/document.xml');
    }

    final relsXml = _extractFile(archive, 'word/_rels/document.xml.rels');
    if (relsXml == null) {
      throw const MissingDocxPartException('word/_rels/document.xml.rels');
    }

    // Extract optional parts
    final numberingXml = _extractFile(archive, 'word/numbering.xml');

    // Parse relationships (hyperlinks)
    final relationships = RelationshipResolver.resolve(relsXml);

    // Parse document content
    final content = DocumentParser.parse(
      documentXml,
      relationships,
      numberingXml: numberingXml,
    );

    // Extract metadata from core.xml (if available)
    final metadata = _extractMetadata(archive);

    // Build the document
    final document = DocxDocument(
      title: metadata.title,
      author: metadata.author,
    );

    for (final item in content) {
      if (item is DocxParagraph) {
        document.addParagraph(item);
      } else if (item is DocxTable) {
        document.addTable(item);
      }
    }

    return document;
  }

  /// Decodes the ZIP archive from raw bytes.
  Archive _decodeArchive(Uint8List bytes) {
    try {
      final archive = ZipDecoder().decodeBytes(bytes);
      return archive;
    } on Object {
      throw const InvalidDocxArchiveException();
    }
  }

  /// Extracts a file from the archive as a UTF-8 string.
  String? _extractFile(Archive archive, String path) {
    for (final file in archive) {
      if (file.name == path && file.isFile) {
        return utf8.decode(file.content as List<int>);
      }
    }
    return null;
  }

  /// Extracts title and author from `docProps/core.xml`.
  ({String? title, String? author}) _extractMetadata(Archive archive) {
    final coreXml = _extractFile(archive, 'docProps/core.xml');
    if (coreXml == null) return (title: null, author: null);

    try {
      // Simple extraction without full XML parsing for metadata
      String? title;
      String? author;

      // <dc:title>...</dc:title>
      final titleMatch =
          RegExp(r'<dc:title>(.*?)</dc:title>', dotAll: true).firstMatch(coreXml);
      if (titleMatch != null && titleMatch.group(1)!.isNotEmpty) {
        title = titleMatch.group(1);
      }

      // <dc:creator>...</dc:creator>
      final authorMatch =
          RegExp(r'<dc:creator>(.*?)</dc:creator>', dotAll: true).firstMatch(coreXml);
      if (authorMatch != null && authorMatch.group(1)!.isNotEmpty) {
        author = authorMatch.group(1);
      }

      return (title: title, author: author);
    } on Object {
      return (title: null, author: null);
    }
  }
}
